---
title: "Code"
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```


```{r, tidy_data}
data(ny_noaa) 

set.seed(1)

ny_noaa_clean = ny_noaa %>%
  separate(date, into = c("year", "month", "day"), sep = "-") %>%
  mutate(prcp = prcp/10, 
         tmax = as.numeric(tmax)/10,
         tmin = as.numeric(tmin)/10) %>%
  sample_n(10000)
```

Column {data-width=500}
-----------------------------------------------------------------------

### The distribution of precipitation (0<prcp<100mm) through months
```{r}
ny_noaa_clean %>%
  filter(prcp > 0 & prcp < 100) %>%
  plot_ly(x = ~ month, y = ~ prcp, color = ~ month, type = "box",
          colors = "Set3") %>%
  layout(xaxis = list(title = "Month"),
         yaxis = list(title = "Precipitation(mm)"))
```


### The mean minimum and maximum temperature through years
```{r}
maxmin_ggplot = ny_noaa_clean %>%
  group_by(year) %>%
  summarize(mean_tmax = mean(tmax, na.rm = TRUE),
          mean_tmin = mean(tmin, na.rm = TRUE)) %>%
  pivot_longer(
    mean_tmax:mean_tmin,
    names_to = "maxmin",
    names_prefix = "mean_",
    values_to = "t"
  ) %>%
  ggplot(aes(x = year, y = t, group = maxmin, color = maxmin)) + 
    geom_point() + geom_line() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x = "Year", y = "Temperature")

ggplotly(maxmin_ggplot)
  
```

Column {data-width=500}
-----------------------------------------------------------------------

### The minimum and maximum temperature through months
```{r}
ny_noaa_clean %>%
  filter(!is.na(tmax) & !is.na(tmin)) %>%
  plot_ly(x = ~ tmin, y = ~ tmax, color = ~ month, type = "scatter",
          mode = "markers", alpha = 0.5, colors = "Set3") %>%
  layout(xaxis = list(title = "Minimum Temperature(C)"),
         yaxis = list(title = "Maximum Temperature(C)")) 
```
